separateAo=true
# sun=false
clouds=off

customTexture.alligatorNoiseTex = noise/alligator.bin TEXTURE_3D R8 128 128 128 RED UNSIGNED_BYTE
customTexture.perlinNoiseTex = noise/perlin.bin TEXTURE_2D R8 512 512 RED UNSIGNED_BYTE
customTexture.worleyNoiseTex = noise/worley.bin TEXTURE_2D R8 512 512 RED UNSIGNED_BYTE
